### ISSUE TITLE
note.tsの項目追加をお願いします。

### ISSUE THREAD

**Issue by takasaki376** [qin-salon/qin-memo#56]
figmaの画面にあるデータ項目と、ソースのsrc/models/note.tsのデータ項目が一致していないです。

具体的には

- figmaには日付があるが、note.tsにはない  
- figmaにはタイトル？（太字の方）と本文（太字じゃない方）の２つの値があるが、note.tsにはexcerptのみ  

の２点です。

**Comment by lightsound** [comment]
@takasaki376 
ありがとうございます！

> figmaには日付があるが、note.tsにはない

こちら一旦、適当な日付を入れておいてください。週末には直します🙏

> figmaにはタイトル？（太字の方）と本文（太字じゃない方）の２つの値があるが、note.tsにはexcerptのみ

こちらは想定どおりです。Qin Memoでは実はタイトルすら持たせていません。メモ本文の一行目をタイトルのように表示させる形です！

**Comment by takasaki376** [comment]
承知しました。

>こちらは想定どおりです。Qin Memoでは実はタイトルすら持たせていません。メモ本文の一行目をタイトルのように表示させる形です！

一行目の定義について確認です。
行の区切り文字がEXAMPLE_NOTEだと改行コードで、EXAMPLE_MY_NOTE_LISTは句点（。）になっていますが、両方とも改行コードが正しいでしょうか。

**Comment by lightsound** [comment]
@takasaki376 

改行コードでお願いします！
EXAMPLE_MY_NOTE_LISTは改行コードが無いですねorz
たかさきさん判断で適当に付け足していただくことは可能ですか？💦

**Comment by takasaki376** [comment]
了解しました。やってみます。
